package project;

import project.recommendationandtroubleshooting.model.recommendation.Configuration;
import project.recommendationandtroubleshooting.model.recommendation.InputRecommendation;
import project.recommendationandtroubleshooting.model.recommendation.ConfigurationUsageType;
import project.recommendationandtroubleshooting.model.recommendation.ConfigurationCharacteristicType;
import project.recommendationandtroubleshooting.model.recommendation.Budget;
import project.recommendationandtroubleshooting.model.recommendation.Mobility;
import project.recommendationandtroubleshooting.model.recommendation.Output;
import project.recommendationandtroubleshooting.model.recommendation.Favorite;
import project.recommendationandtroubleshooting.enums.ConfigurationType
import project.recommendationandtroubleshooting.model.User;

import java.util.List;

global List<Configuration> currentlyPopular;


rule "Currently popular configurations - put to favorite by at least 5 users"
    when
    	$c: Configuration($idConf: id)
        accumulate(
         	User($user: this, $favorites: favorites) and
         	List(size > 0) from collect(
         		Favorite($f: this, f.getConfiguration().getId() = $idConf) from $favorites
         	)
         	$users: collectSet($user)
        )
        eval($users.size() >= 5)
    then
        System.out.println("Konfiguracija: " + $c.getId());
        currentlyPopular.add($c);
end








