package project;
import project.recommendationandtroubleshooting.model.recommendation.Configuration;
import project.recommendationandtroubleshooting.model.recommendation.ConfigurationUsageType;
import project.recommendationandtroubleshooting.model.recommendation.ConfigurationCharacteristicType;
import project.recommendationandtroubleshooting.model.recommendation.Budget;
import project.recommendationandtroubleshooting.model.recommendation.Mobility;
import project.recommendationandtroubleshooting.model.recommendation.Favorite;
import project.recommendationandtroubleshooting.enums.ConfigurationType
import project.recommendationandtroubleshooting.model.User;
import java.util.List;
import java.time.LocalDate;
import java.util.*;

rule "Popular in given interval - put to favorite at least 6 times by 4 different users in the given interval_0" 
        agenda-group "interval_popular"
        lock-on-active true
    when
        $pc: Configurations();
        $confs: List() from collect (Configuration());
        $users: List() from collect (User());
        $res: List() from accumulate(
            	    Configuration($c: this, $confId: id) from $confs and
            	    Number($num: intValue() >= 4) from accumulate(
                             	User($user: this, $favorites: favorites) from $users and
                             		Favorite($f: this, $conf: configuration, $conf.id == $confId, putToFavorite >= 6,
                             		dateOfFavorite.after(new Date("Fri May 28 10:00:00 CEST 2021")) == true,
                             		dateOfFavorite.before(new Date("Sun May 30 11:05:24 CEST 2021")) == true
                             		) from $favorites,
                             	count($user)
                            ),
                    collectList($c)
            	)
    then
        System.out.println("Rule: Popular configurations in given interval");
        modify($pc){setConfigurations($res)};
        System.out.println($pc.getConfigurations());
end


