insert into descriptions (id, problem_description) values (1, 'Računar ne može da se upali.');
insert into descriptions (id, problem_description) values (2, 'Računar ne reaguje na power dugme.');
insert into descriptions (id, problem_description) values (3, 'Računar ne prolazi POST.');
insert into descriptions (id, problem_description) values (4, 'Računar prolazi POST.');
insert into descriptions (id, problem_description) values (5, 'Računar ispisuje "system not found".');
insert into descriptions (id, problem_description) values (6, 'Računar krene da podiže sistem, ali padne.');
insert into descriptions (id, problem_description) values (7, 'Računaru se zaledio ekran.');
insert into descriptions (id, problem_description) values (8, 'Ne rade miš i/ili tastatura i/ili monitor.');
insert into descriptions (id, problem_description) values (9, 'Računaru ne radi zvuk.');
insert into descriptions (id, problem_description) values (10, 'Računar ima nepravilan ispis na ekranu ili je loše učitao fajl.');
insert into descriptions (id, problem_description) values (11, 'Spora WIFI konekcija.');
insert into descriptions (id, problem_description) values (12, 'WIFI ne ostvaruje konekciju.');
insert into descriptions (id, problem_description) values (13, 'Računar zastajkuje prilikom rada.');
insert into descriptions (id, problem_description) values (14, 'Računar ne učitava video.');
insert into descriptions (id, problem_description) values (15, 'Računar ne učitava slike.');
insert into descriptions (id, problem_description) values (16, 'Računar javlja grešku "Disc full" ili "Disc not ready".');
insert into descriptions (id, problem_description) values (17, 'Računar se pregrejava.');
insert into descriptions (id, problem_description) values (18, 'Računar ne prepoznaje USB.');
insert into descriptions (id, problem_description) values (19, 'Računar ne pamti raspored ikonica na desktop-u.');
insert into descriptions (id, problem_description) values (20, 'Pojavljuje se BSOD (plavi ekran).');
insert into descriptions (id, problem_description) values (21, 'Računar izbacuje "disc error".');