insert into descriptions (  problem_description) values ('Računar ne može da se upali.');
insert into descriptions (  problem_description) values ('Računar ne reaguje na power dugme.');
insert into descriptions (  problem_description) values ('Računar ne prolazi POST.');
insert into descriptions (  problem_description) values ('Računar prolazi POST.');
insert into descriptions (  problem_description) values ('Računar ispisuje "system not found".');
insert into descriptions (  problem_description) values ('Računar krene da podiže sistem, ali padne.');
insert into descriptions (  problem_description) values ('Računaru se zaledio ekran.');
insert into descriptions (  problem_description) values ('Ne rade miš i/ili tastatura i/ili monitor.');
insert into descriptions (  problem_description) values ('Računaru ne radi zvuk.');
insert into descriptions (  problem_description) values ('Računar ima nepravilan ispis na ekranu ili je loše učitao fajl.');
insert into descriptions (  problem_description) values ('Spora WIFI konekcija.');
insert into descriptions (  problem_description) values ('WIFI ne ostvaruje konekciju.');
insert into descriptions (  problem_description) values ('Računar zastajkuje prilikom rada.');
insert into descriptions (  problem_description) values ('Računar ne učitava video.');
insert into descriptions (  problem_description) values ('Računar ne učitava slike.');
insert into descriptions (  problem_description) values ('Računar javlja grešku "Disc full" ili "Disc not ready".');
insert into descriptions (  problem_description) values ('Računar se pregrejava.');
insert into descriptions (  problem_description) values ('Računar ne prepoznaje USB.');
insert into descriptions (  problem_description) values ('Računar ne pamti raspored ikonica na desktop-u.');
insert into descriptions (  problem_description) values ('Pojavljuje se BSOD (plavi ekran).');
insert into descriptions (  problem_description) values ('Računar izbacuje "disc error".');