insert into solutions (id, solution) values (1, 'Proveriti da li je računar uključen u struju i proveriti ispravnost power dugmeta.');
insert into solutions (id, solution) values (2, 'Odneti na dalju dijagnostiku u servis.');
insert into solutions (id, solution) values (3, 'Neka periferija računara je blokirana, proveriti priključene uređaje.');
insert into solutions (id, solution) values (4, 'Izvaditi RAM iz memorije kako bi se NV-RAM ponovo napunio, vratiti RAM i zatim ponovo resetovati računar.');
insert into solutions (id, solution) values (5, 'Neka komponenta računara crkava i daje loš napon, odneti na detaljnu dijagnostiku u servis.');
insert into solutions (id, solution) values (6, 'Proveriti da li je u bios-u izabran default-ni butabilni medijum.');
insert into solutions (id, solution) values (7, 'Crkao je disk sa butabilnim medijum ili je loše napajanje, odneti na  detaljnu dijagnostiku u servis.');
insert into solutions (id, solution) values (8, 'Proveriti da li je protokol po kome radi disk ispravan.');
insert into solutions (id, solution) values (9, 'Pogledati da li operativni sistem ima svoj alat za dijagnostiku zašto se nije podigao (npr. safe mode).');
insert into solutions (id, solution) values (10, 'Pogledati u event viewer-u koja aplikacija/periferija je izazvala grešku.');
insert into solutions (id, solution) values (11, 'Pogledati fizičko stanje računara (napomena: pogledati da li su svi kondezatori dobri).');
insert into solutions (id, solution) values (12, 'Izvaditi eksterni disk i pogledati da li disk ima loše sektore.');
insert into solutions (id, solution) values (13, 'Odraditi rekolaciju podataka ako nije na butabilnom delu diska.');
insert into solutions (id, solution) values (14, 'Pogledati da li je konektor dobro priključen.');
insert into solutions (id, solution) values (15, 'Restartovati računar, postoji šansa da nije dobro učitao čip.');
insert into solutions (id, solution) values (16, 'Čip je izgubio kontakt ili je crkao, odneti na detaljnu dijagnostiku u servis.');
insert into solutions (id, solution) values (17, 'Diskonektovati računar sa mreže i ponovo ga konektovati.');
insert into solutions (id, solution) values (18, 'Pronaći bolji signal zatim diskonektovati računar sa mreže i ponovo ga konektovati .');
insert into solutions (id, solution) values (19, 'Premalo RAM memorije, ugraditi dodatno još ako je to moguće.');
insert into solutions (id, solution) values (20, 'Operativni sistem nema dovoljno memorije.');
insert into solutions (id, solution) values (21, 'Disk je prepunjen temporalnom i keš memorijom, očititi je.');
insert into solutions (id, solution) values (22, 'Osloboditi prostora na disku (premestiti/obrisati podatke).');
insert into solutions (id, solution) values (23, 'Promeniti kodek koji se koristi.');
insert into solutions (id, solution) values (24, 'Promeniti softver za gledanje slika.');
insert into solutions (id, solution) values (25, 'Očstiti računar od prašine.');
insert into solutions (id, solution) values (26, 'Proveriti ispravnost rada ventilatora, otvora za hlađenje i da li je kućište ispravno.');
insert into solutions (id, solution) values (27, 'Proveriti sa alatom (npr. HWInfo) da li se procesor ili neka druga komponenta pregrejavaju.');
insert into solutions (id, solution) values (28, 'Proveriti da li su instalirani odgovarajući drajveri.');
insert into solutions (id, solution) values (29, 'Proveriti napon USB port-a.');
insert into solutions (id, solution) values (30, 'Keš memorija je korumpirana, iskorititi program koji briše korumpiranu memoriju.');
insert into solutions (id, solution) values (31, 'Pronaći u event viewer-u koji je kod greške u pitanju.');