insert into solutions ( solution) values ('Proveriti da li je računar uključen u struju i proveriti ispravnost power dugmeta.');
insert into solutions ( solution) values ('Odneti na dalju dijagnostiku u servis.');
insert into solutions ( solution) values ('Neka periferija računara je blokirana, proveriti priključene uređaje.');
insert into solutions ( solution) values ('Izvaditi RAM iz memorije kako bi se NV-RAM ponovo napunio, vratiti RAM i zatim ponovo resetovati računar.');
insert into solutions ( solution) values ('Neka komponenta računara crkava i daje loš napon, odneti na detaljnu dijagnostiku u servis.');
insert into solutions ( solution) values ('Proveriti da li je u bios-u izabran default-ni butabilni medijum.');
insert into solutions ( solution) values ('Crkao je disk sa butabilnim medijum ili je loše napajanje, odneti na  detaljnu dijagnostiku u servis.');
insert into solutions ( solution) values ('Proveriti da li je protokol po kome radi disk ispravan.');
insert into solutions ( solution) values ('Pogledati da li operativni sistem ima svoj alat za dijagnostiku zašto se nije podigao (npr. safe mode).');
insert into solutions ( solution) values ('Pogledati u event viewer-u koja aplikacija/periferija je izazvala grešku.');
insert into solutions ( solution) values ('Pogledati fizičko stanje računara (napomena: pogledati da li su svi kondezatori dobri).');
insert into solutions ( solution) values ('Izvaditi eksterni disk i pogledati da li disk ima loše sektore.');
insert into solutions ( solution) values ('Odraditi rekolaciju podataka ako nije na butabilnom delu diska.');
insert into solutions ( solution) values ('Pogledati da li je konektor dobro priključen.');
insert into solutions ( solution) values ('Restartovati računar, postoji šansa da nije dobro učitao čip.');
insert into solutions ( solution) values ('Čip je izgubio kontakt ili je crkao, odneti na detaljnu dijagnostiku u servis.');
insert into solutions ( solution) values ('Diskonektovati računar sa mreže i ponovo ga konektovati.');
insert into solutions ( solution) values ('Pronaći bolji signal zatim diskonektovati računar sa mreže i ponovo ga konektovati .');
insert into solutions ( solution) values ('Premalo RAM memorije, ugraditi dodatno još ako je to moguće.');
insert into solutions ( solution) values ('Operativni sistem nema dovoljno memorije, osloboditi memoriju sa dela diska gde je operativni sistem');
insert into solutions ( solution) values ('Disk je prepunjen temporalnom i keš memorijom, očititi je.');
insert into solutions ( solution) values ('Osloboditi prostora na disku (premestiti/obrisati podatke).');
insert into solutions ( solution) values ('Promeniti kodek koji se koristi.');
insert into solutions ( solution) values ('Promeniti softver za gledanje slika.');
insert into solutions ( solution) values ('Očstiti računar od prašine.');
insert into solutions ( solution) values ('Proveriti ispravnost rada ventilatora, otvora za hlađenje i da li je kućište ispravno.');
insert into solutions ( solution) values ('Proveriti sa alatom (npr. HWInfo) da li se procesor ili neka druga komponenta pregrejavaju.');
insert into solutions ( solution) values ('Proveriti da li su instalirani odgovarajući drajveri.');
insert into solutions ( solution) values ('Proveriti napon USB port-a.');
insert into solutions ( solution) values ('Keš memorija je korumpirana, iskorititi program koji briše korumpiranu memoriju.');
insert into solutions ( solution) values ('Pronaći u event viewer-u koji je kod greške u pitanju.');
insert into solutions ( solution) values ('Pokušati na drugom USB portu ili sa drugim kablom.');
insert into solutions ( solution) values ('Uraditi memory test kako bi se proverila radna memorijam, možda je loše inicijalizovna.');
insert into solutions ( solution) values ('Pogledali da li radna memorija dobro stoji, možda je do kontakt greške.');