insert into user_authority (user_id, authority_id) values (1,1);
insert into user_authority (user_id, authority_id) values (2,2);
insert into user_authority (user_id, authority_id) values (3,2);
insert into user_authority (user_id, authority_id) values (4,2);
insert into user_authority (user_id, authority_id) values (5,2);
insert into user_authority (user_id, authority_id) values (6,2);
insert into user_authority (user_id, authority_id) values (7,2);
insert into user_authority (user_id, authority_id) values (8,2);
insert into user_authority (user_id, authority_id) values (9,2);
