package project.recommendationandtroubleshooting.repository;

import org.springframework.data.jpa.repository.JpaRepository;

import project.recommendationandtroubleshooting.model.recommendation.ConfigurationCharacteristicTypeRequirements;

public interface ConfigurationCharacteristicTypeRequirementsRepository extends JpaRepository<ConfigurationCharacteristicTypeRequirements, Integer> {

}
