package project;

import project.recommendationandtroubleshooting.model.recommendation.ConfigurationClass;
import project.recommendationandtroubleshooting.model.recommendation.Configurations;
import project.recommendationandtroubleshooting.model.recommendation.ConfigurationUsageType;
import project.recommendationandtroubleshooting.model.recommendation.ConfigurationCharacteristicType;
import project.recommendationandtroubleshooting.model.recommendation.Budget;
import project.recommendationandtroubleshooting.model.recommendation.Mobility;
import project.recommendationandtroubleshooting.model.recommendation.Favorite;
import project.recommendationandtroubleshooting.model.recommendation.Rating;
import project.recommendationandtroubleshooting.enums.ConfigurationType
import project.recommendationandtroubleshooting.model.User;

import java.util.List;

query "Average rating" (Long configurationId)
	$c: ConfigurationClass(id == configurationId, $ratings: ratings);
	$average:= Number() from accumulate (
		Rating($rate: rate) from $ratings,
		average($rate));
end;

query "Number of users by rate" (Long configurationId)
	$c: ConfigurationClass(id == configurationId, $ratings: ratings);
	$one: Number() from accumulate (
		Rating(rate == 1) from $ratings,
		count(1));
	$two: Number() from accumulate (
		Rating(rate == 2) from $ratings,
		count(1));
	$three: Number() from accumulate (
		Rating(rate == 3) from $ratings,
		count(1));
	$four: Number() from accumulate (
		Rating(rate == 4) from $ratings,
		count(1));
	$five: Number() from accumulate (
		Rating(rate == 5) from $ratings,
		count(1));
end;


