package project.recommendationandtroubleshooting.recommendation;
import project.recommendationandtroubleshooting.model.recommendation.InputRequirements;
import project.recommendationandtroubleshooting.model.recommendation.Recommendations;
import project.recommendationandtroubleshooting.model.recommendation.ConfigurationUsageTypeRequirements;
import project.recommendationandtroubleshooting.model.recommendation.Configuration;
import project.recommendationandtroubleshooting.model.recommendation.SetString;
import java.util.List;
import java.util.Set;


query checkIfSetIsEmpty(Set entity)
	eval(entity.size() != 0)
end;



query getConfigurationsByUsage(Set reqCPU, Set reqGPU, Set reqRAM, Set reqOS, Set reqPSU,
		Set reqDiscType, Set reqDiscSize, Set reqMotherboard, Set reqScreenSize,
        Set reqScreenResolution, Set reqMusicCard,
        Set reqTouchscreen, Set reqMicrophone, Set reqCamera, Set reqErgonomic)
    checkIfSetIsEmpty(reqCPU;)
    checkIfSetIsEmpty(reqGPU;)
    checkIfSetIsEmpty(reqRAM;)
    checkIfSetIsEmpty(reqOS;)
    checkIfSetIsEmpty(reqPSU;)
    checkIfSetIsEmpty(reqDiscType;)
    checkIfSetIsEmpty(reqDiscSize;)
    checkIfSetIsEmpty(reqMotherboard;)
    checkIfSetIsEmpty(reqScreenSize;)
    checkIfSetIsEmpty(reqScreenResolution;)
    checkIfSetIsEmpty(reqTouchscreen;)
    checkIfSetIsEmpty(reqMicrophone;)
    checkIfSetIsEmpty(reqCamera;)
    checkIfSetIsEmpty(reqErgonomic;)

	$configuraion: Configuration(
                  (CPU not memberOf reqCPU)
                  ||
                  (GPU not memberOf reqGPU)
                  ||
                  (RAM not memberOf reqRAM)
                  ||
                  (OS not memberOf reqOS)
                  ||
                  (PSU not memberOf reqPSU)
                  ||
                  (discType not memberOf reqDiscType)
                  ||
                  (motherboard not memberOf reqMotherboard)
                  ||
                  (screenSize not memberOf reqScreenSize)
                  ||
                  (screenResolution not memberOf reqScreenResolution)
                  ||
                  (touchscreen not memberOf reqTouchscreen)
                  ||
                  (microphone not memberOf reqMicrophone)
                  ||
                  (camera not memberOf reqCamera)
                  ||
                  (ergonomic not memberOf reqErgonomic)
                 )
end;

    //?checkIfSetIsEmpty(reqCPU, $notEmmptyCPU;)
    //?checkIfSetIsEmpty($reqGPU, $notEmmptyGPU;)
    //?checkIfSetIsEmpty($reqRAM, $notEmmptyRAM;)
    //?checkIfSetIsEmpty($reqOS, $notEmmptyOS;)
    //?checkIfSetIsEmpty($reqPSU, $notEmmptyPSU;)
    //?checkIfSetIsEmpty($reqDiscType, $notEmmptyDiscType;)
    //?checkIfSetIsEmpty($reqDiscSize, $notEmmptyDiscSize;)
    //?checkIfSetIsEmpty($reqMotherboard, $notEmmptyMotherboard;)
    //?checkIfSetIsEmpty($reqScreenSize, $notEmmptyScreenSize;)
    //?checkIfSetIsEmpty($reqScreenResolution, $notEmmptyScreenResolution;)
    //?checkIfSetIsEmpty($reqMusicCard, $notEmmptyMusicCard;)
    //?checkIfSetIsEmpty($reqTouchscreen, $notEmmptyTouchscreen;)
    //?checkIfSetIsEmpty($reqMicrophone, $notEmmptyMicrophone;)
    //?checkIfSetIsEmpty($reqCamera, $notEmmptyCamera;)
    //?checkIfSetIsEmpty($reqErgonomic, $notEnotEmmptyErgonomicmpty;)

rule "Usage"
        agenda-group "recommendation"
	    salience (3)
    when
        $r: Recommendations(configurations.isEmpty())
        $i: InputRequirements($usageType: configurationUsageType);
        $usage: String() from $usageType.getUsage();
        $requirements: ConfigurationUsageTypeRequirements($u: usage, $u.getUsage() == $usage,
        $reqCPU: CPU, $reqGPU: GPU, $reqRAM: RAM, $reqOS: OS, $reqPSU: PSU, $reqDiscType: discType,
        $reqDiscSize: discSize, $reqMotherboard: motherboard, $reqScreenSize: screenSize,
        $reqScreenResolution: screenResolution, $reqMusicCard: musicCard,
        $reqTouchScreen: touchscreen, $reqMicrophone: microphone, $reqCamera: camera, $reqEgronomic: ergonomic);

		$c: Configuration( $configurationId: id, considered == true )
        getConfigurationsByUsage($reqCPU, $reqGPU, $reqRAM, $reqOS, $reqPSU, $reqDiscType,
        $reqDiscSize, $reqMotherboard, $reqScreenSize,
        $reqScreenResolution, $reqMusicCard,
        $reqTouchScreen, $reqMicrophone, $reqCamera, $reqEgronomic;)
    then
        System.out.println("Rule: Usage");
    	modify($c) { setConsidered(false) }
end





/*
package project.recommendationandtroubleshooting.recommendation;
import project.recommendationandtroubleshooting.model.recommendation.InputRequirements;
import project.recommendationandtroubleshooting.model.recommendation.Recommendations;
import project.recommendationandtroubleshooting.model.recommendation.ConfigurationUsageTypeRequirements;
import project.recommendationandtroubleshooting.model.recommendation.Configuration;
import java.util.List;

rule "Usage"
        agenda-group "recommendation"
	    salience (3)
    when
        $r: Recommendations(configurations.isEmpty())
        $i: InputRequirements($usageType: configurationUsageType);
        $usage: String() from $usageType.getUsage();
        $requirements: ConfigurationUsageTypeRequirements($u: usage, $u.getUsage() == $usage,
        $reqCPU: CPU, $reqGPU: GPU, $reqRAM: RAM, $reqOS: OS, $reqPSU: PSU, $reqDiscType: discType,
        $reqDiscSize: discSize, $reqMotherboard: motherboard, $reqScreenSize: screenSize,
        $reqScreenResolution: screenResolution, $reqMusicCard: musicCard,
        $reqTouchScreen: touchscreen, $reqMicrophone: microphone, $reqCamera: camera, $reqEgronomic: ergonomic);

        $configurations: List() from collect(Configuration(considered == true));
        $c: Configuration(
    		(CPU not memberOf $reqCPU && !$reqCPU.isEmpty())
    		||
            (GPU not memberOf $reqGPU && !$reqGPU.isEmpty())
            ||
            (RAM not memberOf $reqRAM && !$reqRAM.isEmpty())
            ||
            (OS not memberOf $reqOS && !$reqOS.isEmpty())
            ||
            (PSU not memberOf $reqPSU && !$reqPSU.isEmpty())
            ||
            (discType not memberOf $reqDiscType && !$reqDiscType.isEmpty())
            ||
            (discSize not memberOf $reqDiscSize && !$reqDiscSize.isEmpty())
            ||
            (motherboard not memberOf $reqMotherboard && !$reqMotherboard.isEmpty())
            ||
            (screenSize not memberOf $reqScreenSize && !$reqScreenSize.isEmpty())
            ||
            (screenResolution not memberOf $reqScreenResolution && !$reqScreenResolution.isEmpty())
            ||
            (musicCard not memberOf $reqMusicCard && !$reqMusicCard.isEmpty())
            ||
            (touchscreen not memberOf $reqTouchScreen && !$reqTouchScreen.isEmpty())
            ||
            (microphone memberOf $reqMicrophone && !$reqMicrophone.isEmpty())
            ||
            (camera not memberOf $reqCamera && !$reqCamera.isEmpty())
            ||
            (ergonomic not memberOf $reqEgronomic && !$reqEgronomic.isEmpty())
    	)
    	from $configurations
    then
        System.out.println("Rule: Usage");
    	modify($c) { setConsidered(false) }
end
*/




